<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Jint" Version="4.16.4" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.12" />
    <PackageReference Include="System.Security.Cryptography.ProtectedData" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Languages\*.json" LogicalName="Languages/%(Filename)%(Extension)" />
  </ItemGroup>

</Project>
